import Link from "next/link";
import { AppShell } from "@/components/layout/AppShell";
import { practiceQuestionTypeLabels } from "@/features/practice/constants";
import { getPracticeOverview } from "@/features/practice/queries";

export const dynamic = "force-dynamic";

export default async function PracticePage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const params = await searchParams;
  const data = await getPracticeOverview(params);
  return <AppShell active="练习中心"><div className="page-header"><div><div className="eyebrow">PRACTICE CENTER</div><h1>练习中心</h1><p className="subtitle">通过练习题检查知识掌握情况，并自动维护错题本。</p></div><Link className="secondary-button" href="/wrong-answers">错题本（{data.currentWrongCount}）</Link></div><div className="grid stats practice-stats"><div className="card"><div className="stat-label">题目总数</div><div className="stat-value">{data.totalQuestions}</div></div><div className="card"><div className="stat-label">已练习</div><div className="stat-value">{data.attemptedQuestionCount}</div></div><div className="card"><div className="stat-label">当前错题</div><div className="stat-value">{data.currentWrongCount}</div></div></div><form className="card practice-filters" method="get"><select name="course" defaultValue={data.params.course}><option value="">全部课程</option>{data.courses.map((course) => <option value={course.slug} key={course.slug}>{course.name}</option>)}</select><select name="type" defaultValue={data.params.type ?? ""}><option value="">全部题型</option>{Object.entries(practiceQuestionTypeLabels).map(([type, label]) => <option value={type} key={type}>{label}</option>)}</select><select name="difficulty" defaultValue={data.params.difficulty?.toString() ?? ""}><option value="">全部难度</option>{[1,2,3,4,5].map((difficulty) => <option value={difficulty} key={difficulty}>难度 {difficulty}</option>)}</select><select name="knowledgePoint" defaultValue={data.params.knowledgePoint}><option value="">全部知识点</option>{data.knowledgePoints.map((point) => <option value={point.slug} key={point.slug}>{point.title}</option>)}</select><button className="secondary-button" type="submit">筛选</button><Link className="text-button" href="/practice">清空</Link></form>{data.questions.length === 0 ? <div className="empty card practice-empty">当前还没有练习题。<p><Link href="/admin">前往内容管理创建题目</Link>（管理后台仅适合本机或可信网络）。</p></div> : <div className="practice-list">{data.questions.map((question) => <article className="card practice-list-item" key={question.id}><div><div className="practice-item-heading"><h2>{question.question.split("\n")[0].slice(0, 100)}</h2><span>{practiceQuestionTypeLabels[question.type]}</span></div><p>{question.knowledgePoint.course.name} · {question.knowledgePoint.title} · 难度 {question.difficulty}/5</p><small>{question.latestAttempt ? question.latestAttempt.isCorrect ? "最近答对" : "最近答错" : "未练习"}{question.attemptCount > 0 && ` · 已作答 ${question.attemptCount} 次`}</small></div><Link className="secondary-button" href={`/practice/${question.id}`}>{question.latestAttempt ? "再次练习" : "开始练习"}</Link></article>)}</div>}</AppShell>;
}
