import Link from "next/link";
import { AppShell } from "@/components/layout/AppShell";
import { SearchForm } from "@/components/search/SearchForm";
import { getSearchFilters, getSearchResults, parseSearchParams, type SearchParamsInput } from "@/features/search/queries";

export const dynamic = "force-dynamic";

export default async function SearchPage({ searchParams }: { searchParams: Promise<SearchParamsInput> }) {
  const raw = await searchParams;
  const params = parseSearchParams(raw);
  const filters = await getSearchFilters();
  const results = params.q ? await getSearchResults(params) : { knowledgePoints: [], courses: [], books: [] };
  const total = results.knowledgePoints.length + results.courses.length + results.books.length;
  return <AppShell active="知识库"><div className="page-header"><div><div className="eyebrow">知识库</div><h1>全局搜索</h1><p className="subtitle">搜索知识点、课程和教材内容。</p></div></div><div className="search-page-form"><SearchForm initialQuery={params.q} course={params.course} book={params.book} /></div><div className="search-filters"><span>按课程筛选</span>{filters.map((course) => <Link className={params.course === course.slug ? "filter-active" : ""} href={`/search?q=${encodeURIComponent(params.q)}&course=${course.slug}`} key={course.slug}>{course.name}</Link>)}{params.course && <Link href={`/search?q=${encodeURIComponent(params.q)}`}>清除筛选</Link>}</div>{!params.q ? <div className="empty card search-empty">输入关键词开始搜索。</div> : total === 0 ? <div className="empty card search-empty">没有找到与“{params.q}”相关的内容。{params.course && <><br /><Link href={`/search?q=${encodeURIComponent(params.q)}`}>返回所有课程</Link></>}</div> : <div className="search-results">{results.knowledgePoints.length > 0 && <section className="search-group"><div className="section-heading"><h2>知识点</h2><span>{results.knowledgePoints.length} 条</span></div>{results.knowledgePoints.map((point) => <Link className="search-result card" href={`/knowledge/${point.slug}`} key={point.slug}><div><h3>{point.title}</h3><p>{point.course.name}{point.summary ? ` · ${point.summary}` : ""}</p></div><div className="result-meta"><span>{point.category}</span><strong>{"★".repeat(point.importance)}{"☆".repeat(5 - point.importance)}</strong><small>复试 {point.interviewImportance}/5</small></div></Link>)}</section>}{results.courses.length > 0 && <section className="search-group"><div className="section-heading"><h2>课程</h2><span>{results.courses.length} 条</span></div>{results.courses.map((course) => <Link className="search-result card" href={`/courses/${course.slug}`} key={course.slug}><div><h3>{course.name}</h3><p>{course.description || "暂无课程简介"}</p></div><small>{course._count.books} 本教材 · {course._count.knowledgePoints} 个知识点</small></Link>)}</section>}{results.books.length > 0 && <section className="search-group"><div className="section-heading"><h2>教材</h2><span>{results.books.length} 条</span></div>{results.books.map((book) => <Link className="search-result card" href={`/books/${book.id}`} key={book.id}><div><h3>{book.title}</h3><p>{book.course.name} · {[book.author, book.publisher, book.edition].filter(Boolean).join(" · ") || "暂无出版信息"}</p></div></Link>)}</section>}</div>}</AppShell>;
}
