"use server";

import { Prisma } from "@prisma/client";
import { revalidatePath } from "next/cache";
import { prisma } from "@/lib/db";
import { chapterInputSchema, courseInputSchema, bookInputSchema, subjectAreaInputSchema, type ChapterInput, type CourseInput, type BookInput, type SubjectAreaInput } from "./schemas";
import { chapterLevel, isDescendant, type ChapterRecord } from "./tree";

const fail = (error: unknown, fallback: string) => error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002" ? "该 slug 已存在。" : fallback;
function refresh(courseSlug?: string, bookId?: string) { for (const path of ["/admin", "/admin/structure", "/courses", "/search", ...(courseSlug ? [`/courses/${courseSlug}`] : []), ...(bookId ? [`/books/${bookId}`, `/admin/books/${bookId}/chapters`] : [])]) { try { revalidatePath(path); } catch { /* Server Action tests may run without a request context. */ } } }

export async function saveSubjectArea(input: SubjectAreaInput) { const parsed = subjectAreaInputSchema.safeParse(input); if (!parsed.success) return { ok: false, error: parsed.error.issues[0]?.message ?? "专业方向参数无效。" } as const; try { const saved = parsed.data.id ? await prisma.subjectArea.update({ where: { id: parsed.data.id }, data: { name: parsed.data.name, slug: parsed.data.slug, description: parsed.data.description, sortOrder: parsed.data.sortOrder } }) : await prisma.subjectArea.create({ data: parsed.data }); refresh(); return { ok: true, id: saved.id } as const; } catch (error) { return { ok: false, error: fail(error, "专业方向保存失败，请稍后重试。") } as const; } }
export async function deleteSubjectArea(id: string) { const area = await prisma.subjectArea.findUnique({ where: { id }, select: { _count: { select: { courses: true } } } }); if (!area) return { ok: true } as const; if (area._count.courses) return { ok: false, error: "该专业方向仍包含课程，请先移动或解除这些课程后再删除。" } as const; try { await prisma.subjectArea.delete({ where: { id } }); refresh(); return { ok: true } as const; } catch { return { ok: false, error: "专业方向删除失败，请稍后重试。" } as const; } }

export async function saveCourse(input: CourseInput) { const parsed = courseInputSchema.safeParse(input); if (!parsed.success) return { ok: false, error: parsed.error.issues[0]?.message ?? "课程参数无效。" } as const; if (parsed.data.subjectAreaId && !await prisma.subjectArea.findUnique({ where: { id: parsed.data.subjectAreaId }, select: { id: true } })) return { ok: false, error: "专业方向不存在。" } as const; try { const saved = parsed.data.id ? await prisma.course.update({ where: { id: parsed.data.id }, data: { name: parsed.data.name, slug: parsed.data.slug, subjectAreaId: parsed.data.subjectAreaId ?? null, description: parsed.data.description, sortOrder: parsed.data.sortOrder } }) : await prisma.course.create({ data: parsed.data }); refresh(saved.slug); return { ok: true, id: saved.id } as const; } catch (error) { return { ok: false, error: fail(error, "课程保存失败，请稍后重试。") } as const; } }
export async function deleteCourse(id: string) { const course = await prisma.course.findUnique({ where: { id }, select: { slug: true, _count: { select: { books: true, knowledgePoints: true } } } }); if (!course) return { ok: true } as const; if (course._count.books || course._count.knowledgePoints) return { ok: false, error: `该课程仍包含 ${course._count.books} 本教材和 ${course._count.knowledgePoints} 个知识点，不能删除。` } as const; try { await prisma.course.delete({ where: { id } }); refresh(); return { ok: true } as const; } catch { return { ok: false, error: "课程删除失败，请稍后重试。" } as const; } }

export async function saveBook(input: BookInput) { const parsed = bookInputSchema.safeParse(input); if (!parsed.success) return { ok: false, error: parsed.error.issues[0]?.message ?? "教材参数无效。" } as const; const course = await prisma.course.findUnique({ where: { id: parsed.data.courseId }, select: { id: true, slug: true } }); if (!course) return { ok: false, error: "课程不存在。" } as const; try { if (parsed.data.id) { const existing = await prisma.book.findUnique({ where: { id: parsed.data.id }, select: { id: true, courseId: true } }); if (!existing) return { ok: false, error: "教材不存在。" } as const; if (existing.courseId !== parsed.data.courseId) { const mismatch = await prisma.chapterKnowledgePoint.count({ where: { chapter: { bookId: parsed.data.id }, knowledgePoint: { courseId: { not: parsed.data.courseId } } } }); if (mismatch) return { ok: false, error: "该教材已有知识点关联与目标课程不一致，请先调整教材章节中的知识点关联或知识点课程。" } as const; } await prisma.book.update({ where: { id: parsed.data.id }, data: { courseId: parsed.data.courseId, title: parsed.data.title, author: parsed.data.author, publisher: parsed.data.publisher, edition: parsed.data.edition, isbn: parsed.data.isbn, description: parsed.data.description, cover: parsed.data.cover, sortOrder: parsed.data.sortOrder } }); refresh(course.slug, parsed.data.id); return { ok: true, id: parsed.data.id } as const; } const book = await prisma.book.create({ data: parsed.data }); refresh(course.slug, book.id); return { ok: true, id: book.id } as const; } catch (error) { return { ok: false, error: fail(error, "教材保存失败，请稍后重试。") } as const; } }
export async function deleteBook(id: string) { const book = await prisma.book.findUnique({ where: { id }, select: { course: { select: { slug: true } }, _count: { select: { chapters: true } } } }); if (!book) return { ok: true } as const; if (book._count.chapters) return { ok: false, error: "该教材仍包含章节，请先删除空的章节后再删除教材。" } as const; try { await prisma.book.delete({ where: { id } }); refresh(book.course.slug, id); return { ok: true } as const; } catch { return { ok: false, error: "教材删除失败，请稍后重试。" } as const; } }

async function getBookChapterRecords(bookId: string) { return prisma.chapter.findMany({ where: { bookId }, select: { id: true, bookId: true, parentId: true, level: true, sortOrder: true } }); }
async function validateChapterParent(input: ChapterInput, existingId?: string) { const chapters = await getBookChapterRecords(input.bookId); const parent = input.parentId ? chapters.find((chapter) => chapter.id === input.parentId) : null; if (input.parentId && !parent) return { error: "父章节不存在或不属于当前教材。" as const }; if (existingId && input.parentId === existingId) return { error: "章节不能设置自己为父章节。" as const }; if (existingId && input.parentId && isDescendant(chapters, existingId, input.parentId)) return { error: "章节不能移动到自己的子孙章节下。" as const }; return { chapters, parent: parent ?? null };
}
export async function saveChapter(input: ChapterInput) { const parsed = chapterInputSchema.safeParse(input); if (!parsed.success) return { ok: false, error: parsed.error.issues[0]?.message ?? "章节参数无效。" } as const; const existing = parsed.data.id ? await prisma.chapter.findUnique({ where: { id: parsed.data.id }, select: { id: true, bookId: true } }) : null; if (parsed.data.id && !existing) return { ok: false, error: "章节不存在。" } as const; if (existing && existing.bookId !== parsed.data.bookId) return { ok: false, error: "章节不能移动到其他教材。" } as const; let checked: Awaited<ReturnType<typeof validateChapterParent>>; try { checked = await validateChapterParent(parsed.data, existing?.id); } catch (error) { return { ok: false, error: error instanceof Error ? error.message : "章节父子关系无效。" } as const; } if ("error" in checked) return { ok: false, error: checked.error } as const; const level = chapterLevel(checked.parent); try { const saved = await prisma.$transaction(async (tx) => { const chapter = existing ? await tx.chapter.update({ where: { id: existing.id }, data: { title: parsed.data.title, number: parsed.data.number, parentId: parsed.data.parentId ?? null, sortOrder: parsed.data.sortOrder, level } }) : await tx.chapter.create({ data: { bookId: parsed.data.bookId, title: parsed.data.title, number: parsed.data.number, parentId: parsed.data.parentId ?? null, sortOrder: parsed.data.sortOrder, level } }); const all = await tx.chapter.findMany({ where: { bookId: parsed.data.bookId }, select: { id: true, parentId: true, level: true } }); const descendants = new Map<string, string[]>(); for (const item of all) if (item.parentId) descendants.set(item.parentId, [...(descendants.get(item.parentId) ?? []), item.id]); const visited = new Set<string>(); const updateDescendants = async (parentId: string, parentLevel: number) => { if (visited.has(parentId)) throw new Error("章节树数据存在循环，请先修复结构。"); visited.add(parentId); for (const childId of descendants.get(parentId) ?? []) { await tx.chapter.update({ where: { id: childId }, data: { level: parentLevel + 1 } }); await updateDescendants(childId, parentLevel + 1); } }; await updateDescendants(chapter.id, chapter.level); return chapter; }); refresh(undefined, saved.bookId); return { ok: true, id: saved.id } as const; } catch (error) { return { ok: false, error: fail(error, "章节保存失败，请稍后重试。") } as const; } }
export async function deleteChapter(id: string) { const chapter = await prisma.chapter.findUnique({ where: { id }, select: { bookId: true, _count: { select: { children: true, knowledgePoints: true } } } }); if (!chapter) return { ok: true } as const; if (chapter._count.children) return { ok: false, error: "该章节仍包含子章节，不能删除。" } as const; if (chapter._count.knowledgePoints) return { ok: false, error: "该章节仍有关联知识点，不能删除。" } as const; try { await prisma.chapter.delete({ where: { id } }); refresh(undefined, chapter.bookId); return { ok: true } as const; } catch { return { ok: false, error: "章节删除失败，请稍后重试。" } as const; } }

export async function validateChapterKnowledgePointCourse(chapterId: string, knowledgePointId: string) { const record = await prisma.chapter.findUnique({ where: { id: chapterId }, select: { book: { select: { courseId: true } } } }); const point = await prisma.knowledgePoint.findUnique({ where: { id: knowledgePointId }, select: { courseId: true } }); if (!record || !point) return false; return record.book.courseId === point.courseId; }
