import Link from "next/link";
import { AppShell } from "@/components/layout/AppShell";
import { KnowledgeListActions } from "@/components/admin/KnowledgeListActions";
import { getAdminKnowledgeList } from "@/features/content-management/queries";
import { ReviewStatus } from "@prisma/client";
import { knowledgeCategoryLabels } from "@/features/knowledge/category-labels";

export const dynamic = "force-dynamic";

const statusLabels: Record<ReviewStatus, string> = { AI_DRAFT: "AI 草稿", REVIEWED: "已审核", VERIFIED: "已确认" };

export default async function AdminKnowledgePage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const params = await searchParams;
  const data = await getAdminKnowledgeList(params);
  const query = new URLSearchParams(); if (data.params.q) query.set("q", data.params.q); if (data.params.course) query.set("course", data.params.course); if (data.params.reviewStatus) query.set("reviewStatus", data.params.reviewStatus);
  return <AppShell active="内容管理"><div className="page-header"><div><div className="eyebrow">KNOWLEDGE POINTS</div><h1>知识点管理</h1><p className="subtitle">共 {data.total} 个知识点，当前第 {data.page} / {data.pageCount} 页。</p></div><Link className="primary-button" href="/admin/knowledge/new">新建知识点</Link></div><form className="admin-filters card" method="get"><input name="q" defaultValue={data.params.q} placeholder="搜索标题、摘要或定义" maxLength={100} /><select name="course" defaultValue={data.params.course}><option value="">全部课程</option>{data.courses.map((course) => <option value={course.slug} key={course.slug}>{course.name}</option>)}</select><select name="reviewStatus" defaultValue={data.params.reviewStatus ?? ""}><option value="">全部状态</option>{Object.entries(statusLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><button className="secondary-button" type="submit">筛选</button><Link className="text-button" href="/admin/knowledge">清空</Link></form><div className="admin-table-wrap card"><table className="admin-table"><thead><tr><th>标题</th><th>slug</th><th>课程</th><th>类别</th><th>状态</th><th>重要度</th><th>更新时间</th><th>操作</th></tr></thead><tbody>{data.items.length ? data.items.map((item) => <tr key={item.id}><td><Link className="table-link" href={`/knowledge/${item.slug}`}>{item.title}</Link></td><td><code>{item.slug}</code></td><td>{item.course.name}</td><td>{knowledgeCategoryLabels[item.category]}</td><td><span className="status-pill">{statusLabels[item.reviewStatus]}</span></td><td>★{item.importance} / 复试 ★{item.interviewImportance}</td><td>{item.updatedAt.toLocaleDateString("zh-CN")}</td><td><div className="table-actions"><Link href={`/knowledge/${item.slug}`}>查看</Link><Link href={`/admin/knowledge/${item.id}/edit`}>编辑</Link><KnowledgeListActions id={item.id} title={item.title} formulaCount={item.formulas.length} exampleCount={item.examples.length} relationCount={item.outgoingRelations.length + item.incomingRelations.length} chapterCount={item.chapters.length} /></div></td></tr>) : <tr><td colSpan={8} className="empty">没有匹配的知识点。</td></tr>}</tbody></table></div><div className="pagination">{data.page > 1 ? <Link className="secondary-button" href={`/admin/knowledge?${new URLSearchParams([...query, ["page", String(data.page - 1)]])}`}>上一页</Link> : <span className="secondary-button disabled">上一页</span>}<span>第 {data.page} 页</span>{data.page < data.pageCount ? <Link className="secondary-button" href={`/admin/knowledge?${new URLSearchParams([...query, ["page", String(data.page + 1)]])}`}>下一页</Link> : <span className="secondary-button disabled">下一页</span>}</div></AppShell>;
}
