"use client";

import { useState, useTransition } from "react";
import { importKnowledgeBundleAction, previewKnowledgeBundleAction } from "@/features/content-transfer/actions";

type Course = { id: string; name: string; slug: string };
type Preview = { subjectAreas: { create: number; update: number }; courses: { create: number; update: number }; knowledgePoints: { create: number; update: number }; formulas: { create: number; update: number }; examples: { create: number; update: number }; relations: { create: number; update: number }; errors: number; warnings: number };

export function ContentTransferPanel({ courses }: { courses: Course[] }) {
  const [course, setCourse] = useState(""); const [json, setJson] = useState(""); const [preview, setPreview] = useState<Preview | null>(null); const [previewedJson, setPreviewedJson] = useState<string | null>(null); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [pending, startTransition] = useTransition();
  const updateJson = (next: string) => { setJson(next); setPreview(null); setPreviewedJson(null); setMessage(""); setError(""); };
  const previewBundle = () => { setError(""); setMessage(""); startTransition(async () => { const result = await previewKnowledgeBundleAction(json); if (!result.ok) { setError(result.errors.join("\n")); setPreview(null); setPreviewedJson(null); } else { setPreview(result.summary); setPreviewedJson(json); } }); };
  const importBundle = () => { if (!preview || !previewedJson || previewedJson !== json || !window.confirm("确认导入这个 Knowledge Bundle？导入采用 Merge/Upsert，不会删除缺失内容，也不会修改笔记、收藏和学习记录。")) return; setError(""); startTransition(async () => { const result = await importKnowledgeBundleAction(previewedJson); if (!result.ok) setError(result.errors.join("\n")); else { setMessage(`导入完成：创建知识点 ${result.result.createdKnowledgePoints}，更新知识点 ${result.result.updatedKnowledgePoints}，公式 ${result.result.formulas}，案例 ${result.result.examples}，关系 ${result.result.relations}。`); setPreview(null); setPreviewedJson(null); } }); };
  return <div className="transfer-grid"><section className="card transfer-card"><h2>导出知识内容</h2><p>可导出全部知识内容，或按已有课程筛选。Book、Chapter 和用户学习数据不会进入 Bundle。</p><div className="transfer-row"><select value={course} onChange={(event) => setCourse(event.target.value)}><option value="">全部课程</option>{courses.map((item) => <option value={item.slug} key={item.slug}>{item.name}</option>)}</select><a className="primary-button" href={`/api/admin/content-export${course ? `?course=${encodeURIComponent(course)}` : ""}`}>下载 JSON</a></div></section><section className="card transfer-card"><h2>导入知识内容</h2><p>支持粘贴或选择不超过 2 MB 的 JSON。必须先预览，再确认写入。</p><input type="file" accept=".json,application/json" onChange={(event) => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 2 * 1024 * 1024) { updateJson(""); setError("Knowledge Bundle 超过 2 MB 限制。"); return; } const reader = new FileReader(); reader.onload = () => updateJson(typeof reader.result === "string" ? reader.result : ""); reader.readAsText(file); }} /><textarea className="bundle-textarea" value={json} onChange={(event) => updateJson(event.target.value)} placeholder="粘贴 Knowledge Bundle JSON" rows={18} />{error && <pre className="transfer-error">{error}</pre>}{message && <p className="transfer-success">{message}</p>}<div className="transfer-actions"><button className="secondary-button" type="button" disabled={pending || !json.trim()} onClick={previewBundle}>{pending ? "处理中…" : "验证并预览"}</button>{preview && previewedJson === json && <button className="primary-button" type="button" disabled={pending} onClick={importBundle}>确认导入</button>}</div>{preview && previewedJson === json && <div className="import-preview"><h3>导入预览</h3>{Object.entries({ 专业方向: preview.subjectAreas, 课程: preview.courses, 知识点: preview.knowledgePoints, 公式: preview.formulas, 案例: preview.examples, 关系: preview.relations }).map(([label, value]) => <div className="preview-row" key={label}><span>{label}</span><span>创建 {value.create} · 更新 {value.update}</span></div>)}<div className="preview-row"><span>错误 / 警告</span><span>{preview.errors} / {preview.warnings}</span></div></div>}</section></div>;
}
