"use client";

import { useState, useTransition } from "react";
import { deleteKnowledgeQuestion, saveKnowledgeQuestion } from "@/features/content-management/actions";
import type { InterviewAnswerType } from "@prisma/client";

type Question = { id: string; question: string; level: number; frequency: number; source: string | null; answers: Array<{ answerType: InterviewAnswerType; content: string }> };
const fields: Array<[keyof FormState, string]> = [["shortAnswer", "简短回答"], ["standardAnswer", "标准回答"], ["deepAnswer", "深入理解"]];
type FormState = { id?: string; question: string; level: string; frequency: string; source: string; shortAnswer: string; standardAnswer: string; deepAnswer: string };
const emptyForm = (): FormState => ({ question: "", level: "1", frequency: "3", source: "", shortAnswer: "", standardAnswer: "", deepAnswer: "" });

export function KnowledgeQuestionEditor({ knowledgePointId, questions }: { knowledgePointId: string; questions: Question[] }) {
  const [form, setForm] = useState<FormState>(emptyForm()); const [error, setError] = useState(""); const [pending, startTransition] = useTransition();
  const edit = (question: Question) => { const answerMap = new Map(question.answers.map((answer) => [answer.answerType, answer.content])); setForm({ id: question.id, question: question.question, level: String(question.level), frequency: String(question.frequency), source: question.source ?? "", shortAnswer: answerMap.get("SHORT_30S") ?? "", standardAnswer: answerMap.get("MEDIUM_1MIN") ?? "", deepAnswer: answerMap.get("DEEP") ?? "" }); setError(""); };
  const save = () => { setError(""); startTransition(async () => { const result = await saveKnowledgeQuestion({ ...form, knowledgePointId, level: Number(form.level), frequency: Number(form.frequency), source: form.source || null, shortAnswer: form.shortAnswer || null, standardAnswer: form.standardAnswer || null, deepAnswer: form.deepAnswer || null }); if (!result.ok) setError(result.error); else window.location.reload(); }); };
  const remove = (id: string) => { if (!window.confirm("确认删除这条常见问法及其回答？")) return; startTransition(async () => { const result = await deleteKnowledgeQuestion({ id, knowledgePointId }); if (!result.ok) setError(result.error); else window.location.reload(); }); };
  return <section className="card editor-section"><h2>常见问法</h2>{questions.map((question) => <div className="managed-item" key={question.id}><strong>{question.question}</strong><span>常见程度 {question.frequency}/5 · 难度 {question.level}/5</span><div><button type="button" disabled={pending} onClick={() => edit(question)}>编辑</button><button type="button" disabled={pending} onClick={() => remove(question.id)}>删除</button></div></div>)}<div className="managed-form"><input placeholder="问题" value={form.question} onChange={(e) => setForm({ ...form, question: e.target.value })} /><div className="form-grid"><label>难度（1-5）<input type="number" min="1" max="5" value={form.level} onChange={(e) => setForm({ ...form, level: e.target.value })} /></label><label>问答重要度（1-5）<input type="number" min="1" max="5" value={form.frequency} onChange={(e) => setForm({ ...form, frequency: e.target.value })} /></label></div><input placeholder="来源（可选）" value={form.source} onChange={(e) => setForm({ ...form, source: e.target.value })} />{fields.map(([name, label]) => <label key={name}>{label}<textarea rows={4} placeholder={`${label}（Markdown，可选）`} value={form[name]} onChange={(e) => setForm({ ...form, [name]: e.target.value })} /></label>)}<div><button type="button" disabled={pending || !form.question.trim()} onClick={save}>{pending ? "保存中…" : form.id ? "保存问法" : "新增问法"}</button>{form.id && <button type="button" disabled={pending} onClick={() => setForm(emptyForm())}>取消编辑</button>}</div></div>{error && <p className="action-error" role="alert">{error}</p>}</section>;
}
