"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { saveBook, saveChapter, saveCourse, saveSubjectArea } from "@/features/structure-management/actions";
import type { BookInput, ChapterInput, CourseInput, SubjectAreaInput } from "@/features/structure-management/schemas";

type Option = { id: string; name: string; slug?: string };
type Values = Record<string, string>;

export function StructureForm({ kind, initial = {}, options = [], areas = [], bookId, chapterOptions = [] }: { kind: "area" | "course" | "book" | "chapter"; initial?: Values; options?: Option[]; areas?: Option[]; bookId?: string; chapterOptions?: Option[] }) {
  const [values, setValues] = useState<Values>({ sortOrder: "0", ...initial, ...(bookId ? { bookId } : {}) });
  const [error, setError] = useState(""); const [pending, startTransition] = useTransition(); const router = useRouter();
  const set = (key: string, value: string) => setValues((current) => ({ ...current, [key]: value }));
  const submit = (event: React.FormEvent) => { event.preventDefault(); setError(""); startTransition(async () => { const result = kind === "area" ? await saveSubjectArea({ ...values, sortOrder: Number(values.sortOrder) } as unknown as SubjectAreaInput) : kind === "course" ? await saveCourse({ ...values, subjectAreaId: values.subjectAreaId || null, sortOrder: Number(values.sortOrder) } as unknown as CourseInput) : kind === "book" ? await saveBook({ ...values, courseId: values.courseId, sortOrder: Number(values.sortOrder) } as unknown as BookInput) : await saveChapter({ ...values, bookId: values.bookId ?? bookId ?? "", parentId: values.parentId || null, number: values.number || null, sortOrder: Number(values.sortOrder) } as unknown as ChapterInput); if (!result.ok) setError(result.error ?? "保存失败。"); else router.push(kind === "chapter" ? `/admin/books/${values.bookId ?? bookId}/chapters` : "/admin/structure"); }); };
  const title = kind === "area" ? "专业方向" : kind === "course" ? "课程" : kind === "book" ? "教材" : "章节";
  return <form className="card structure-form" onSubmit={submit}><h2>{values.id ? `编辑${title}` : `新建${title}`}</h2>{(kind === "area" || kind === "course") && <><label>名称<input required value={values.name ?? ""} onChange={(e) => set("name", e.target.value)} /></label><label>slug<input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={values.slug ?? ""} onChange={(e) => set("slug", e.target.value)} /></label><label>简介<textarea value={values.description ?? ""} onChange={(e) => set("description", e.target.value)} /></label></>}{kind === "course" && <label>专业方向<select value={values.subjectAreaId ?? ""} onChange={(e) => set("subjectAreaId", e.target.value)}><option value="">无专业方向</option>{areas.map((area) => <option value={area.id} key={area.id}>{area.name}</option>)}</select></label>}{kind === "book" && <><label>所属课程<select required value={values.courseId ?? ""} onChange={(e) => set("courseId", e.target.value)}>{options.map((option) => <option value={option.id} key={option.id}>{option.name}</option>)}</select></label><label>书名<input required value={values.title ?? ""} onChange={(e) => set("title", e.target.value)} /></label><div className="form-grid"><label>作者<input value={values.author ?? ""} onChange={(e) => set("author", e.target.value)} /></label><label>出版社<input value={values.publisher ?? ""} onChange={(e) => set("publisher", e.target.value)} /></label><label>版本<input value={values.edition ?? ""} onChange={(e) => set("edition", e.target.value)} /></label><label>ISBN<input value={values.isbn ?? ""} onChange={(e) => set("isbn", e.target.value)} /></label></div><label>描述<textarea value={values.description ?? ""} onChange={(e) => set("description", e.target.value)} /></label><label>封面 URL / 路径<input value={values.cover ?? ""} onChange={(e) => set("cover", e.target.value)} placeholder="/media/books/xxx.jpg 或 https://..." /></label></>}{kind === "chapter" && <><label>章节标题<input required value={values.title ?? ""} onChange={(e) => set("title", e.target.value)} /></label><div className="form-grid"><label>章节编号<input value={values.number ?? ""} onChange={(e) => set("number", e.target.value)} /></label><label>父章节<select value={values.parentId ?? ""} onChange={(e) => set("parentId", e.target.value)}><option value="">根章节</option>{chapterOptions.filter((option) => option.id !== values.id).map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label></div></>}{kind !== "chapter" || true ? <label>排序<input type="number" min="0" required value={values.sortOrder ?? "0"} onChange={(e) => set("sortOrder", e.target.value)} /></label> : null}{error && <p className="action-error">{error}</p>}<div className="transfer-actions"><button className="primary-button" type="submit" disabled={pending}>{pending ? "保存中…" : "保存"}</button><button className="secondary-button" type="button" disabled={pending} onClick={() => router.back()}>取消</button></div></form>;
}
